### ISSUE TITLE
Question (問題請教)

### ISSUE THREAD

**Issue by ymcasky** [auroua/InsightFace_TF#6]
請問為什麼是用這個
Can I ask why using this train_op instead of another train_op below?

```
grads = opt.compute_gradients(total_loss)
update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
with tf.control_dependencies(update_ops):
train_op = opt.apply_gradients(grads, global_step=global_step)
```

而不是這個呢?
`# train_op = opt.minimize(total_loss, global_step=global_step)`

**Comment by auroua** [comment]
Because the `L_Resnet_E_IR_RBN.py` use `tf.layers.batch_normalization`. The `moving_mean` and `moving_variance` of `tl.layers.batch_normalization` need to be updated in this way.  You can reference [tl.layers.batch_normalization](https://www.tensorflow.org/api_docs/python/tf/layers/batch_normalization).

**Comment by ymcasky** [comment]
Thanks!
